### ISSUE TITLE
Can't Find furi_hal_version.c

### ISSUE THREAD

**Issue by Turtleqwe** [FroggMaster/FlipperZero#3]
I searched the SD for "furi_hal_version.c" and i couldn't find it. I don't know if you have to add it or something.....

**Comment by FroggMaster** [comment]
That file will not be located on your SD Card as it's part of the actual Flipper Zero firmware. The steps you're commenting on are in regards to modifying the firmware you're running to adjust the name of your device. Once you change this code it requires you to recompile the firmware and flash it to your device. 

You can take a closer look at: 
https://github.com/FroggMaster/FlipperZero/blob/main/Notes%20and%20Documentation/Change%20Flippers%20Display%20Name.md

Which overviews forking a Firmware, modifying the appropriate line of the code and then recompiling your firmware.
